version: '3'

services:
  postgres:
    container_name: mydash-pg
    image: 'postgres:11.6'
    environment:
      POSTGRES_DB: "mydash-dev"
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      - '<path to the mydash-server directory>/seeds:/tmp/seeds'
    networks:
      - backend

  mydash-server:
    container_name: "mydash-server"
    build: ./mydash-server
    env_file: '<path to the mydash-server directory>/.env'
    networks:
      - backend
      - frontend
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=postgres
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mydash-dev

  mydash-client:
    container_name: "mydash-client"
    build: ./mydash-client
    command: 'npm start'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - 'node_modules:/app/node_modules'
      - '/<path to the mydash-client directory>:/app'
    networks:
      - frontend
    ports:
      - '3000:3000'
    depends_on:
      - mydash-server

volumes:
  postgres: 
  node_modules:

networks:
  frontend:
  backend: